title: Doug Toppin's Blog
author: dougtoppin
email: dougtoppin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have been in software systems development for my entire career and am a private pilot.  I used to think I might be able to turn being a pilot into a job but am still waiting for the US Air Force to call me up.  My interests include software systems, cloud stuff, specifically AWS, and all of the related cool services it provides. These include Step Functions, Lambda, Fargate, CloudFormation, cdk and numerous others. I also have a variety of technology, film-making and political interests and am always willing to talk about any of them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.dougtoppin.name" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dougtoppin
github_username:  dougtoppin
google_analytics: UA-38327782-1
disqus:
    shortname: dougtoppinsblog
#plugins:
#  - jekyll-sitemap

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
